export default {
  SHOW_CONTRIBUTIONS: 'SHOW_CONTRIBUTIONS',
  SHOW_DAILY_RETURN: 'SHOW_DAILY_RETURN',
  SHOW_PF_INDEX: 'SHOW_PF_INDEX',
  SHOW_PF_VALUE: 'SHOW_PF_VALUE',
  CHANGE_START_DATE: 'CHANGE_START_DATE',
  CHANGE_FINISH_DATE: 'CHANGE_FINISH_DATE',
};
